name: Release Stone Prover for Fedora

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TARGET_ARCH: x86_64

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image (Fedora)
      run: |
        docker buildx build --target test --file Dockerfile.fedora --load -t stone-prover-fedora-test .

    - name: Run tests in Fedora container
      run: |
        docker run --rm -v $(pwd):/app stone-prover-fedora-test /bin/bash -c "
        cd /app &&
        chmod +x ./test.sh &&
        ./test.sh
        "
        
    - name: Set version output
      id: vars
      run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

    - name: Build target Docker image (Fedora)
      run: |
        docker buildx build --target target --file Dockerfile.fedora --load -t stone-prover-fedora .

    - name: Extract binaries from Docker image
      run: |
        docker create --name temp stone-prover-fedora
        docker cp temp:/usr/bin/cpu_air_prover ./cpu_air_prover-${TARGET_ARCH}
        docker cp temp:/usr/bin/cpu_air_verifier ./cpu_air_verifier-${TARGET_ARCH}
        docker rm temp

    - name: Package RPM
      run: |
        docker run --rm -v $(pwd):/rpmbuild/SOURCES stone-prover-fedora \
          bash -c "dnf install -y rpm-build && \
                   mkdir -p /rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS} && \
                   cp /rpmbuild/SOURCES/stone-prover.spec /rpmbuild/SPECS/ && \
                   rpmbuild -ba /rpmbuild/SPECS/stone-prover.spec \
                   --define \"version ${{ steps.vars.outputs.tag }}\" \
                   --define \"_topdir /rpmbuild\""

    - name: Rename RPM package
      run: |
        mv ./RPMS/x86_64/*.rpm ./stone-prover-fedora-${TARGET_ARCH}.rpm

    - name: Verify file existence
      run: |
        ls -la ./
        ls -la ./RPMS/x86_64/

    - name: Upload files to GitHub release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          ./cpu_air_prover-${TARGET_ARCH}
          ./cpu_air_verifier-${TARGET_ARCH}
          ./stone-prover-fedora-${TARGET_ARCH}.rpm
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}